### ISSUE TITLE
Not working on macOS Monterey 12.3

### ISSUE THREAD

**Issue by dtoub** [bradmontgomery/alfred-percent-change#5]
Python is gone from this seed of Monterey, and even after reinstalling Python 2.7.18 and even Python 3, the % change workflow is not working at all. Any thoughts on an update? Thanks.

**Comment by bradmontgomery** [comment]
@dtoub Try the latest release and let me know if this helps. https://github.com/bradmontgomery/alfred-percent-change/blob/v1.6.0/PercentChange1-6.alfredworkflow

**Comment by dtoub** [comment]
Perfect! And I also added a Copy to Clipboard function at the end, so I’m all good. Thanks for getting back to me.

Best regards,

David
